name = "Probably"
uuid = "9b0cda1b-512d-4e6e-9b30-63a9b611bfba"
authors = ["Mike Innes <mike.j.innes@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
